name: Article to Read
description: Capture an article you want to read later
title: ""
labels: ["article"]
body:
  - type: markdown
    attributes:
      value: |
        Quickly capture an article to read. Only title and URL are required - add scheduling and notes as needed.

  - type: input
    id: article-title
    attributes:
      label: Article Title
      description: What is the title of the article?
      placeholder: e.g., The Future of Artificial Intelligence
    validations:
      required: true

  - type: input
    id: article-url
    attributes:
      label: Article URL
      description: Provide the link to the article
      placeholder: https://example.com/article
    validations:
      required: true

  - type: input
    id: due-date
    attributes:
      label: Due Date (Optional)
      description: When do you want to read this? Format YYYY-MM-DD
      placeholder: e.g., 2025-12-20
    validations:
      required: false

  - type: textarea
    id: initial-notes
    attributes:
      label: Initial Notes (Optional)
      description: Why does this look interesting? Any context or key points to remember?
      placeholder: |
        Quick thoughts on why this caught your attention...
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        **Categorization**: After creating the issue, add topic labels in the format `topic:category/subcategory` (e.g., `topic:pl/compilers`, `topic:math/category-theory`)
